name: sggm
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.1.2
  url_launcher: ^6.3.1
  flutter_secure_storage: ^9.2.2

  firebase_core: ^3.8.1
  firebase_messaging: ^15.1.5
  flutter_local_notifications: ^18.0.1
  dio: ^5.9.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/

  fonts:
    - family: Inknut_Antiqua
      fonts:
        - asset: assets/fonts/Inknut_Antiqua/InknutAntiqua-Regular.ttf
        - asset: assets/fonts/Inknut_Antiqua/InknutAntiqua-Light.ttf
        - asset: assets/fonts/Roboto/Roboto-Regular.ttf