name: sggm
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.1

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations: 
    sdk: flutter

  provider: ^6.1.2
  url_launcher: ^6.3.1
  flutter_secure_storage: ^9.2.2

  firebase_core: ^3.8.1
  firebase_messaging: ^15.1.5
  flutter_local_notifications: ^18.0.1
  dio: ^5.9.1
  intl: ^0.20.2
  local_auth: ^2.3.0 
  local_auth_android: ^1.0.44
  local_auth_darwin: ^1.4.1
  local_auth_windows: ^1.0.11
  youtube_player_flutter: ^9.0.3
  webview_flutter: ^4.9.0
  shimmer: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_launcher_icons: ^0.13.1
  mocktail: ^1.0.4
  build_runner: ^2.4.7

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icon/app_icon.png"

  adaptive_icon_background: "#0F1A17"
  adaptive_icon_foreground: "assets/icon/app_icon.png"

flutter:
  uses-material-design: true

  assets:
    - assets/

  fonts:
    - family: Inknut_Antiqua
      fonts:
        - asset: assets/fonts/Inknut_Antiqua/InknutAntiqua-Regular.ttf
        - asset: assets/fonts/Inknut_Antiqua/InknutAntiqua-Light.ttf
        - asset: assets/fonts/Roboto/Roboto-Regular.ttf